services:
  - type: web
    name: netflix-top-lists
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.app:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
